<div class="sideBox">
<h3>Download Info</h3>
<p>
    <label>Author:</label>
    <?php echo $author; ?> <br />
    <label>Version:</label>
    <?php echo $version; ?><br />
    <label>Downloads:</label>
    <cite><?php $counter=CMDM_number_of_downloads(); echo $counter; ?> Download<?php if ($counter>1 || $counter==0) echo 's'; ?></cite> <br />
      <label>Updated:</label>
    <?php echo $updated; ?><br />
    
	
<div class="supported">
<?php if ($adminSupported): ?>Recommended<?php endif; ?>
<div class="clear"></div>

</div>
</div>