<div class="sideBox">
<h3><?php _e('Download Info', 'cm-download-manager'); ?></h3>
<p>
    <label><?php _e('Author', 'cm-download-manager'); ?>:</label>
    <?php echo $author; ?> <br />
    <label><?php _e('Version', 'cm-download-manager'); ?>:</label>
    <?php echo $version; ?><br />
    <label><?php _e('Downloads', 'cm-download-manager'); ?>:</label>
    <cite><?php $counter=CMDM_number_of_downloads(); printf(_n('1 Download', '%d Downloads', $counter, 'cm-download-manager'), $counter); ?></cite> <br />
      <label><?php _e('Updated', 'cm-download-manager'); ?>:</label>
    <?php echo $updated; ?><br />
    
	
<div class="supported">
<?php if ($adminSupported): ?><?php _e('Recommended', 'cm-download-manager'); ?><?php endif; ?>
<div class="clear"></div>

</div>
</div>