<div class="topicTblWrapper">
    <table class="topicTbl" style="position:relative">
        <thead>
            <tr>
                <th>Topic</th>
                <th>Posts</th>
                <th>Last Poster</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody id="threadsContainer">
            <?php
            do_action('CMDM_show_support_threads_list', $items);
            ?>
        </tbody>
    </table>
</div>
<?php
$perPage = 10;
$pages = ceil($total / $perPage);
$currentPage = 1;
?>
<div class="paging"><a href="#" class="prev">&laquo;</a>
    <a href="#" class="currentPage" data-page="1">1</a>
    <?php for ($i = 2; $i <= $pages; $i++): ?>
        <a href="#" data-page="<?php echo $i; ?>"><?php echo $i; ?></a> 
    <?php endfor; ?>
    <a href="#" class="next">&raquo;</a></div>
<!--/paging -->
<script>
</script>
<div class="boxWhite694">
    <form id="addThreadForm" action="<?php the_permalink($post->ID); ?>/topic/add" method="post" style="position:relative">
        <h5>Leave your comment/question</h5>
        <ul class="CMDM_error" style="display:none"></ul>
        <ul class="notes">
            <li>Allow markup: &lt;strong&gt;, &lt;em&gt;, &lt;a&gt;</li>
            <li>Wrap your code using &lt;pre&gt;&lt;/pre&gt;</li>
        </ul>
        <input type="text" name="thread_title" placeholder="Title" autocomplete="off"/><br />
        <textarea name="thread_comment" cols="" rows="" placeholder="What is your comment about?"></textarea>
        <label>
            <input name="thread_notify" type="checkbox" value="1"/>
            Notify me of follow</label>
        <button class="butPost">Post &gt;</button>
    </form>
</div>
<script>
    var totalSupportPages = <?php echo $pages; ?>;
    jQuery(document).ready(function($) {
        $('.tabItemSupport .paging a').live('click', function(e) {
            e.preventDefault();
            var currentPageItem = $('.tabItemSupport .paging a.currentPage');
            var currentPage = parseInt(currentPageItem.data('page'));
            var selectedItem = $(this);
            if (selectedItem.hasClass('prev')) {
                showSupportPage(currentPage-1);
            } else if (selectedItem.hasClass('next')) {
                showSupportPage(currentPage+1);
            } else {
                showSupportPage(selectedItem.data('page'));
            }
            
        });
        function showSupportPage(pageNum, force) {
            force = typeof force !== 'undefined' ? force : false;
            var currentPageItem = $('.tabItemSupport .paging a.currentPage');
            var currentPage = parseInt(currentPageItem.data('page'));
            
            if (pageNum<1) pageNum=1;
            if (pageNum>totalSupportPages) pageNum=totalSupportPages;
            if (!force && pageNum==currentPage) return false;
            else {
                currentPageItem.removeClass('currentPage');
                $.ajax({
                    url: '<?php the_permalink(); ?>/topic/page/'+pageNum,
                    dataType: 'html',
                    beforeSend: function() {
                        $('#threadsContainer').append('<div class="CMDM_loadingOverlay"></div>');
                    },
                    success: function(data) {
                        $('#threadsContainer').html(data);
                        $('.tabItemSupport .paging a[data-page='+pageNum+']').addClass('currentPage');
                    }
                });
            }
            
        }
        $('#addThreadForm').ajaxForm({
            dataType: 'json',
            beforeSubmit: function(arr, $form) {
                $form.append('<div class="CMDM_loadingOverlay"></div>');
                $form.find('.CMDM_error').empty().hide();
            },
            success: function(data, status, xhr, $form) {
            
                if (data.success==1) {
                    $form.find('.CMDM_loadingOverlay').remove();
                    $form.resetForm();
                    showSupportPage(1, true);
                    
                } else {
                    for (var i=0; i<data.message.length; i++)
                        $form.find('.CMDM_error').append('<li>'+data.message[i]+'</li>').show().delay(5000).fadeOut('slow');
                    $form.find('.CMDM_loadingOverlay').remove();
                }
            }
        });
    });
</script>
