<p class="clear">
<br />
<h1><strong>CM Download Manager Pro </strong></h1>
 <p><strong>A Pro version of CM Downloads is <a href="http://www.cminds.com/downloads/cm-download-manager-pro/"  target="new">available here</a></strong></p>
 <p>CM Download Manager Pro is a Premium version of <a title="CM Downloads" href="http://www.cminds.com/plugins/cm-downloads/" target="new">CM Download</a></p>
This plugin adds many more features and functionality to <a title="CM Downloads" href="http://www.cminds.com/plugins/cm-downloads/" target="new">CM Downloads Plugin</a>, giving the admin better tools to customize the Downloads system behavior, adding login support from social networks, adding password protection support and a lot more.
<h2>Features (Pro Version Only)</h2>
<!--TODO-->
<ul>
<li><strong>Social Media Registration Integration</strong>- Integrates with Facebook &amp; Google+ &amp; LinkedIn (<a href="http://www.cminds.com/wp-content/uploads/edd/image1.png" target="new">image-1</a>) (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image2.png" target="new">image-2</a>)</li>
<li><strong>Shortcodes/Widgets</strong>- Generate top contributors, recent updates and most download items list</li>
<li><strong>View Restriction</strong>- Define per each download if it is open to non logged in users and which user roles can view in case only logged-in are allowed. This can be set by Admin or Admin can give user ability to define (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-26-17.jpg">View image</a>) </Li>
<li><strong>Password Protection</strong>- Protect download with password (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-33-08.jpg">View Image</a>)</li>
<li><strong>Upload Restrictions</strong>- Define which user roles can create new downloads (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-39-35.jpg">View Download</a>)</Li>
<li><strong>URL / Shortcode</strong>- Allow to include URL or shortcode in download page instead of uploading a file. This is useful for integration with other plugins and support checkout carts and selling downloads <a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-41-44.jpg">Example of EDD integration</a>) (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-44-14.jpg">Example of User Selection</a>)</Li>
<li><strong>Related Downloads</strong>- Show Related downloads in download page (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-45-53.jpg">View Image</a>)</li>
<li><strong>Downloads Page Tabs</strong>- Show more tabs for download descriptions in download page</Li>
<li><strong>Search</strong>- Filter search results by date, downloads and username</li>
<li><strong>Moderate User Comments</strong>- Admin can moderate user comments (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-47-33.jpg">View Image</a>)</li>
<li><strong>Auto-approve comments and answers from users</strong>- Admin can define a list of users which do not need moderation (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-47-33.jpg">View Image</a>)</li>
<li><strong>Multisite</strong>- Supports multisite</li>
<li><strong>Public User Profile</strong>- Automatically generate a public profile page containing the downloads user posted with link to his social media profile (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-49-22.jpg">View Image</a>)</li>
<li><strong>Gravatar</strong> - Ability to show Gravatar near user name and in user profile (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-49-22.jpg">View Image</a>)</li>
<li><strong>Order Comments</strong> - Show comments in download page in ascending or descending order</li>
<li><strong>Localization Support</strong> - Forntend (user side) is localized</li>
<li><strong>View Count Control</strong> - Control how view count is done (by view or by session)</li>
<li><strong>Gratitude Message</strong> - Does not include Gratitude message in the footer.</li>

</ul>

<h1><strong>Purchase </strong></h1>
<p>The Pro version is only $25. You can purchase the pro version from <a href="http://www.cminds.com/downloads/cm-download-manager-pro/">Here</a></p>


</p>