<p class="clear">
<br />
<h1><strong>CM Download Manager Pro </strong></h1>
 <p><strong>A Pro version of CM Downloads is <a href="http://downloadsmanager.cminds.com"  target="new">available here</a></strong></p>
 <p>CM Download Manager Pro is a Premium version of <a title="CM Downloads" href="http://downloadsmanager.cminds.com" target="new">CM Download</a></p>
This plugin adds many more features and functionality to <a title="CM Downloads" href="http://downloadsmanager.cminds.com" target="new">CM Downloads Plugin</a>, giving the admin better tools to customize the Downloads system behavior, adding login support from social networks, adding password protection support and a lot more.
<h2>Features (Pro Version Only)</h2>
<!--TODO-->
<ul>
<li><strong>Social Media Registration Integration</strong>- Integrates with Facebook &amp; Google+ &amp; LinkedIn: (<a href="http://www.cminds.com/wp-content/uploads/edd/image1.png" target="new">View Image 1</a>) (<a href="http://www.cminds.com/wp-content/uploads/edd/cm-answers-image2.png" target="new">View Image 2</a>)</li>
<li><strong>Shortcodes/Widgets</strong>- Generate top contributors, recent updates and most download items list<br />
<br><br />
Top Downloads - CMDM-top-downloads count="5"&nbsp;"&nbsp; (<a href="http://www.cminds.com/wp-content/uploads/cmdm/CMDM95.png" target="new">View Image</a>)<br><br />
Frequent Contributors - CMDM-frequent-contributors  Cat="category-name" sort="Asc/Desc" count="5"&nbsp;"&nbsp; (<a href="http://www.cminds.com/wp-content/uploads/cmdm/CMDM96.png" target="new">View Image</a>)<br><br />
Downloads List- CMDM-downloads-list Cat="category-name" sort="Asc/Desc" count="5"&nbsp;"&nbsp; (<a href="http://www.cminds.com/wp-content/uploads/cmdm/CMDM98.png" target="new">View Image</a>)<br><br />
Related Downloads - CMDM-related-downloads  Cat="category-name" sort="Asc/Desc" count="5"&nbsp;"&nbsp; (<a href="http://www.cminds.com/wp-content/uploads/cmdm/CMDM97.png" target="new">View Image</a>)<br>
</li>
<li><strong>View Restriction</strong>- Define per each download if it is open to non-logged in users. If only logged in user are allowed, you can also define which user roles can view specific downloads. This can be set by Admin or Admin can give the user ability to define  (<a href="http://www.cminds.com/wp-content/uploads/cmdm/CMDM91.png">View image</a>) </Li>
<li><strong>Password Protection</strong>- Protect downloads with passwords (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-33-08.jpg">View Image</a>), (<a href="http://www.cminds.com/cmdownloads/cm-downloads-pro/" target="_blank">View Demo</a>)</li>
<li><strong>Upload Restrictions</strong>- Define which user roles can create new downloads (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-39-35.jpg">View Image</a>)</Li>
<li><strong>URL / Shortcode</strong>- Allow to include URL or shortcode in download page instead of uploading a file. This is useful for integration with other plugins and support checkout carts and selling downloads. (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-41-44.jpg">Example of EDD integration</a>) , (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-44-14.jpg">Example of User Selection</a>), (<a href="http://www.cminds.com/cmdownloads/cm-answers-pro/" target="_blank">View Demo</a>)</Li>
<li><strong>Related Downloads</strong>- Show Related downloads on the download page (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-45-53.jpg">View Image</a>), (<a href="http://www.cminds.com/cmdownloads/cm-answers-pro/" target="_blank">View Demo</a>)</li>
<li><strong>Downloads Page Tabs</strong>- Show more tabs for download descriptions in download page, (<a href="http://www.cminds.com/cmdownloads/cm-answers-pro/" target="_blank">View Demo</a>)</Li>
<li><strong>Search</strong>- Filter search results by date, downloads and username&nbsp;(<a href="http://www.cminds.com/cmdownloads/" target="_blank">View Demo</a>)</li>
<li><strong>Moderate User Comments</strong>- Admin can moderate user comments (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-47-33.jpg">View Image</a>)</li>
<li><strong>Auto-approve comments and answers from users</strong>- Admin can define a list of users which do not need moderation (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-47-33.jpg">View Image</a>)</li>
<li><strong>Multisite</strong>- Supports multisite</li>
<li><strong>Public User Profile</strong>- Automatically generate a public profile page containing the downloads each user has posted with link to his social media profile (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-49-22.jpg">View Image</a>)</li>
<li><strong>Gravatar</strong> - Ability to show Gravatar near user name and in user profile (<a href="http://www.cminds.com/wp-content/uploads/edd/22-06-2013-22-49-22.jpg">View Image</a>)</li>
<li><strong>Order Comments</strong> - Show comments in download page in ascending or descending order (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99H.png">Image from Settings</a>)</li>
<li><strong>Localization Support</strong> - Forntend (user side) is localized</li>
<li><strong>View Count</strong> - Show view count for each download and Control how view count is done and what is the initial number it starts at (by view or by session) (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99F.png">Image from Settings</a>), (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99G.png">Image from Downloads edit screen</a>)</li>
<li><strong>Gratitude Message</strong> - Does not include Gratitude message in the footer.</li>
<li><strong>Permalinks</strong> - Ability to change permalink from /cmdownloads to user defined. (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99E.png">Image from Settings</a>)</li>
<li><strong>Support and Tabs control</strong> - Ability to remove support forum and also other tabs from download page. (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99D.png">Image from Settings</a>)</li>
<li><strong>Slide Show</strong> - Ability to turn off slide show. (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99C.png">Image from Settings</a>)</li>
<li><strong>Disclaimer</strong> - Add an option to show disclaimer for first time users.  (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99A.png">Image from Settings</a>),  (<a href="http://downloadsmanager.cminds.com//wp-content/uploads/edd/Downloads99B.png">Image from site</a>)</li>
<li><strong>External Viewer</strong> - Added external link to Google Docs viewer for supported Google Docs document types .  (<a href="http://www.cminds.com/cmdownloads/pdf-file-preview-example/">View Demo</a>)</li>
<li><strong>MP3 Viewer</strong> - Added embedded mp3 player for music files. (<a href="http://www.cminds.com/cmdownloads/mp3-audio-example/">View Demo</a>)</li>
<li><strong>Downloads Index Views</strong> - Option to toggle between list view and tiles view. (<a href="http://www.cminds.com/cmdownloads/">View Demo</a>)</li>
<li><strong>Social Share</strong> – Includes a social share widget in the question page (<a href="http://www.cminds.com/cmdownloads/mp3-audio-example/">View Demo - Widget on the right</a>)</li>

</ul>

<h1><strong>Purchase </strong></h1>
<p>The Pro version is only $25. You can purchase the pro version from <a href="http://downloadsmanager.cminds.com">Here</a></p>


</p>