<div class="CMDM">
<table class="CMDM-dashboard">
    <thead>
	<tr>
	<th colspan=4>
	&nbsp;&nbsp;<a href="<?php echo CMDM_get_url('cmdownload', 'add'); ?>" class="CMDM-add">Add new</a>
	</th>
	</tr>
	<tr>
            <th style="min-width:250px">Title</th>
            <th>Status</th>
            <th >Downloads</th>
            <th style="min-width:200px">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php if (empty($myDownloads)): ?>
            <tr><td colspan="3">You haven't added any downloads yet</td></tr>
        <?php
        else:
            foreach ($myDownloads as $download):
                ?>
            <tr>
                <td><a href="<?php echo get_permalink($download->getId()); ?>"><?php echo $download->getTitle(); ?></a></td>
                <td><?php $status = $download->getStatus(); echo ucfirst($status); ?></td>
                <td align="center"><?php echo $download->getNumberOfDownloads(); ?></td>
                <?php
                if ($status == 'published') $action = 'unpublish';
                else $action = 'publish';
                ?>
                <td><a href="<?php echo CMDM_get_url('cmdownload', $action, array('id'=>$download->getId())); ?>"><?php echo ucfirst($action); ?></a> | 
                    <a href="<?php echo CMDM_get_url('cmdownload', 'edit', array('id'=>$download->getId())); ?>">Edit</a> | 
                    <a href="<?php echo CMDM_get_url('cmdownload', 'del', array('id'=>$download->getId())); ?>" onclick="if (!confirm('Are you sure you want to delete?')) {return false;}">Delete</a>
                </td>
            </tr>
                <?php
            endforeach;
        endif;
        ?>
    </tbody>
</table>
</div>
