<?php
if( !isset($_GET['ajax']) ):
    get_header();
endif;
?><div class="CMDM site-content"><?php
if( have_posts() ):
    while(have_posts()):
        the_post();
        $download = CMDM_GroupDownloadPage::getInstance(get_the_id());
        ?>
            <div class="CMDM-app">
                <div class="rating"><?php do_action('CMDM_show_rating', get_the_id()); ?></div>
                <div class="backtolib"><a href="<?php echo esc_attr(home_url('/cmdownloads')); ?>">&laquo;&nbsp;<?php
                	_e('Back to All Downloads', 'cm-download-manager'); ?></a></div>
                <h2><?php the_title(); ?></h2>
                <!--/h2 -->
                <div class="main">
                    <?php
                    $screenshots = CMDM_get_screenshots();
                    ?>
                    <div class="searchResItems">
                        <div class="scrollable">
                            <div class="items">
                                <?php
                                if( !empty($screenshots) ):
                                    foreach($screenshots as $screenshot):
                                        ?>
                                        <div> <img src="<?php echo esc_attr(CMDM_get_url('cmdownload', 'screenshot', array('size' => '720x220', 'img' => $screenshot)));
                                        	?>" height="220" /> </div>
                                        <?php
                                    endforeach;
                                else:
                                    ?>
                                    <div> <img src="<?php echo esc_attr(CMDM_get_default_screenshot()); ?>" height="220" width="720" alt="Screenshot" /> </div>
                                <?php
                                endif;
                                ?>
                            </div>
                        </div>
                        <!--/scrollable -->
                        <div class="paging"><a href="javascript:void(0)" class="prev browse left">&laquo;</a>
                            <div class="navi"></div>
                            <a href="javascript:void(0)" class="next browse right">&raquo;</a></div>
                        <!--/paging -->
                    </div>
                    <!--/searchResItems -->
                    <ul class="tabNav">
                        <li class="on"><a href="#description"><?php _e('Description', 'cm-download-manager'); ?></a></li>
                        <li><a href="#support"><?php _e('Support', 'cm-download-manager'); ?></a></li>
                    </ul>
                    <div class="boxGrey724">
                        <div class="tabItem">
                            <?php the_content(); ?>

                        </div>
                        <div class="tabItem tabItemSupport"><?php do_action('CMDM_show_support', get_the_id()); ?></div>
                    </div>

                    <!--/boxGrey724 -->
                </div>
                <!--/main -->
                <div class="aside">
                    <?php do_action('CMDM_show_details', get_the_id()); ?>
                    <!--/sideBox -->
                    <?php do_action('CMDM_show_download_button', get_the_id()); ?>
                    <!--/sideBox -->
                    <?php dynamic_sidebar('cm-download-manager-sidebar'); ?>
                </div>
                <!--/aside -->
                <div class="clear"></div>
            </div>
            <!-- javascript coding -->
            <?php
        endwhile;
    endif;
    ?>
</div><?php
if( !isset($_GET['ajax']) ) get_footer();